#!/bin/bash

if [ -e /usr/bin/catvnc ]; then
  JBROOT=
else
  JBROOT=/var/jb
fi

chown root:wheel ${JBROOT}/usr/bin/catvnc
chmod 777 ${JBROOT}/usr/bin/catvnc
chmod +s ${JBROOT}/usr/bin/catvnc

killall -9 catvnc >/dev/null 2>&1

declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
  eval "echo 'finish:reload' >&${cydia[0]}"
else
  killall -9 SpringBoard >/dev/null 2>&1
  killall -9 backboardd >/dev/null 2>&1
fi

echo 'postinst done'
